##################################################################################################
##------------------------------------------FILE START------------------------------------------##
##################################################################################################


# Set minimum ver.
cmake_minimum_required(VERSION 3.10)

# Build the executable.
add_executable(FHMapOfficializer
	main.cpp
	md5.cpp
)

# Include directories to build.
target_include_directories(FHMapOfficializer PRIVATE .)


##################################################################################################
##-------------------------------------------FILE END-------------------------------------------##
##################################################################################################
##-------------------------------------------MODIFIED-------------------------------------------##
## DATE: 9/25/2026                                                                              ##
## TIME: 2:32 PM (UTC-5:00)                                                                     ##
## BY: radioactivedark                                                                          ##
##################################################################################################